register_user:
    path:      /users
    defaults:  {_controller: 'app_controller:registerUserAction'}

register_user_extended:
    path:       /users_extended
    defaults:  {_controller: 'app_controller:registerUserCustomAction'}

error_response:
    path:       /error_response
    defaults:  {_controller: 'app_controller:withErrorResponseAction'}

context_depending:
    path:       /context_depending
    defaults:  {_controller: 'app_controller:contextDependingRequestAction'}

no_custom_request:
    path:       /no_request
    defaults:  {_controller: 'app_controller:noCustomRequestAction'}

validation_results:
    path:       /validation_results
    defaults:  {_controller: 'app_controller:validationResultsAction'}